{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
