name: Flask Application CI/CD

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
    paths:
      - "app/**"
      - "helm/**"
      
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_REGISTRY: 416772749198.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  IMAGE_TAG: ${{ github.sha }}

jobs:
  ####################################
  # CI
  ####################################
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
        ####################################
        # Black checks formatting, Flake8 checks style, Pylint checks for quality issues, and isort organizes imports."
        ####################################
     
      - name: Black
        run: black --check .

      - name: isort
        run: isort --check-only .

      - name: Flake8
        run: flake8 .

      - name: Pylint
        run: pylint app.py tests

      - name: Run Tests
        run: |
          python -m pytest --cov=. --cov-report=xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  ####################################
  # BUILD
  ####################################
  build:

    needs: ci

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${ECR_REPOSITORY}:${IMAGE_TAG} .

      - name: Tag Docker Image
        run: |
          docker tag \
            ${ECR_REPOSITORY}:${IMAGE_TAG} \
            ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

      - name: Push Docker Image
        run: |
          docker push \
            ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

  ####################################
  # DEPLOY
  ####################################

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "$AWS_REGION" \
            --name "$EKS_CLUSTER_NAME"

      - name: Helm Upgrade
        run: |
          helm upgrade --install flask-app ./helm/flask-app \
            --set image.repository="${ECR_REGISTRY}/${ECR_REPOSITORY}" \
            --set image.tag="${IMAGE_TAG}"

          helm upgrade --install monitoring ./helm/monitoring

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/flask-app
          kubectl get pods
          kubectl get svc
